# Schema for the configuration files of the Node Reference module.
node_reference.settings:
  type: config_object
  label: 'Node Reference settings'
  mapping:
    selected_node:
      type: integer
      label: 'The NID of the selected node'
      nullable: true
